name: temple
description: temple .

version: 0.1.0+1
isar_version: &isar_version 3.1.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.1
  visibility_detector: ^0.4.0+2
  lu_foundation:
    git:
      url: 'https://github.com/lwj1994/flutter_lu_foundation'
      ref: 'dev'
  permission_handler:
    git:
      url: https://github.com/baseflow/flutter-permission-handler
      path: permission_handler/
      ref: main
  isar: *isar_version
  isar_flutter_libs: *isar_version
  icloud_storage: ^2.2.0
  dyno: ^0.0.4
  isolate: ^2.1.1
  connectivity_plus: ^5.0.2
  json_annotation: ^4.8.1
  ota_update: ^6.0.0
  package_info_plus: ^5.0.1
  device_info_plus: ^9.1.2
  after_layout: ^1.2.0
  measure_size: ^4.0.0
  url_launcher: ^6.2.4
  card_swiper: ^3.0.1
  app_settings: ^5.1.1
  encrypt: ^5.0.3
  fluttertoast: ^8.2.4
  focus_detector_v2: ^3.1.0+1
  flutter_displaymode: ^0.6.0
  image_picker: ^1.0.7
  photo_view: 0.14.0
  rxdart: 0.27.7
  flutter_riverpod: ^2.4.10
  riverpod_annotation: ^2.3.4
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  path_provider: ^2.1.2
  cached_network_image: ^3.3.1
  auto_route: ^7.8.4
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  #cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  logger: ^2.0.2+1
  build_runner: ^2.4.8
  isar_generator: *isar_version
  json_serializable: ^6.7.1
  retrofit_generator: ^8.1.0
  auto_route_generator: ^7.3.2
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
